title: ULTRA HACK
description: ULTRA HACK (УЛЬТРА РЕЗНЯ) - крутая ролевая система для игры в рискованные приключения в причудливых мирах
theme: just-the-docs
color_scheme: ultra

url: https://ultra-hack.github.io/rules
